### ISSUE TITLE
Latest GTNHLib update breaks FalseTweaks multithreaded rendering

### ISSUE THREAD

**Issue by FalsePattern** [GTNewHorizons/GTNHLib#53]
The changes merged in https://github.com/GTNewHorizons/GTNHLib/pull/44 break the multithreaded renderer inside FalseTweaks.
```
[15:03:07] [Chunk Update Worker #0/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.IllegalStateException: Tried to get the Tessellator off the main thread when not capturing!
[15:03:07] [Chunk Update Worker #0/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.gtnewhorizon.gtnhlib.client.renderer.TessellatorManager.get(TessellatorManager.java:31)
[15:03:07] [Chunk Update Worker #0/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.client.renderer.Tessellator.ft$verifyThread(Tessellator.java:3111)
[15:03:07] [Chunk Update Worker #0/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.client.renderer.Tessellator.handler$zbi000$falsetweaks$verifyThreadIsCorrect(Tessellator.java:3092)
[15:03:07] [Chunk Update Worker #0/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.client.renderer.Tessellator.reset(Tessellator.java)
[15:03:07] [Chunk Update Worker #0/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.client.renderer.Tessellator.discard(Tessellator.java:597)
[15:03:07] [Chunk Update Worker #0/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.falsepattern.falsetweaks.modules.threadedupdates.ThreadedChunkUpdateHelper.runTask(ThreadedChunkUpdateHelper.java:642)
[15:03:07] [Chunk Update Worker #0/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.falsepattern.falsetweaks.modules.threadedupdates.ThreadedChunkUpdateHelper.access$500(ThreadedChunkUpdateHelper.java:67)
[15:03:07] [Chunk Update Worker #0/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.falsepattern.falsetweaks.modules.threadedupdates.ThreadedChunkUpdateHelper$WorkerThread.run(ThreadedChunkUpdateHelper.java:715)
```

**Comment by FalsePattern** [comment]
See also: https://github.com/FalsePattern/FalseTweaks/issues/190
