### ISSUE TITLE
Crash when placing an ItemConduit, only occurs on the server

### ISSUE THREAD

**Issue by SrYthan** [GTNewHorizons/GTNHLib#61]
java.lang.BootstrapMethodError: java.lang.NoSuchMethodError: it.unimi.dsi.fastutil.objects.ObjectArrayList.combine(Lit/unimi/dsi/fastutil/objects/ObjectArrayList;)Lit/unimi/dsi/fastutil/objects/ObjectArrayList;
	at it.unimi.dsi.fastutil.objects.ObjectImmutableList.<clinit>(ObjectImmutableList.java:151)
	at com.gtnewhorizon.gtnhlib.concurrent.cas.CasList.<init>(CasList.java:34)
	at crazypants.enderio.conduit.TileConduitBundle.<init>(TileConduitBundle.java:70)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at com.enderio.core.common.BlockEnder.createTileEntity(BlockEnder.java:66)
	at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:953)
	at net.minecraft.world.World.func_147438_o(World.java:3195)
	at crazypants.enderio.conduit.BlockConduitBundle.getLightOpacity(BlockConduitBundle.java:432)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:682)
	at net.minecraft.world.World.func_147465_d(World.java:841)
	at crazypants.enderio.conduit.AbstractItemConduit.func_77648_a(AbstractItemConduit.java:73)
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:534)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:154)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:493)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:870)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:258)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1026)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:462)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:845)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:695)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: it.unimi.dsi.fastutil.objects.ObjectArrayList.combine(Lit/unimi/dsi/fastutil/objects/ObjectArrayList;)Lit/unimi/dsi/fastutil/objects/ObjectArrayList;
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000)
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1394)
	at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1750)
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477)
	... 28 more

**Comment by SrYthan** [comment]
this crash started after changing the TileConduitBundle class

present in this changelogs below 

https://github.com/GTNewHorizons/EnderIO/compare/2.8.11...2.8.13

**Comment by ah-OOG-ah** [comment]
I can't reproduce this in dev with GTNHLib and EnderIO. If this is still occuring, please reopen it with
- the smallest modlist needed to reproduce the crash
- the exact steps done to produce the crash
- the log file produced, should be `fml-client-latest.log` on the client and `fml-server-latest.log` on the server.
